apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: youssefashraf265/go-web-app-optimized:latest  # Update with your image
          ports:
            - containerPort: 80
          env:
            - name: REDIS_HOST
              value: "redis.db.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: go-app
  namespace: app
spec:
  type: NodePort
  selector:
    app: go-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # Expose on this port
