apiVersion: v1
kind: Service
metadata:
  name: go-app-service
  namespace: app
spec:
  type: NodePort
  selector:
    app: go-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # Expose on this port